import { Link } from 'react-router-dom';
import TextBlock from '../../components/TextBlock';
import classes from './terms-and-conditions.module.scss';

const PrivacyPolicyPage = () => {
  return (
    <div className={classes.wrapper}>
        <div className={`container ${classes.wrapper_container}`} data-aos="fade-up">
            <h2 className={classes.wrapper_ttl}>Privacy Policy</h2>
            <span data-aos="fade-up" className={classes.wrapper_update}>Last Updated July 15, 2022</span>
            <h4 data-aos="fade-up" className={classes.wrapper_ttl_sub}>Introduction</h4>
            <TextBlock classWrap={classes.wrapper_text}>
              <p data-aos="fade-up">FENFO Learning, Inc. (“FENFO”, “us”, or “we”) feels strongly about protecting your privacy. We understand how important privacy is to you, and we are committed to creating a safe and secure environment for everyone. This Privacy Policy applies to FENFO.com, our application programming interface (“API”), and all of our online services applications (collectively, our “platform”), which are all owned and operated by FENFO. This Privacy Policy describes how FENFO collects and uses the information you provide on our platform and describes the choices available to you regarding our use of your personal information and how you can access and update this information.</p>
              <p data-aos="fade-up">Our Privacy Policy describes what information we gather from our members and others who visit and use our platform, how we use that information, and what we do to protect it. By visiting or using our platform, you consent to the information handling practices described in this Privacy Policy.</p>
              <p data-aos="fade-up">Your use of our platform and any information you provide on our platform are subject to the terms of this Privacy Policy, which is incorporated into and subject to our Terms of Service. Any capitalized terms used but not defined within this Privacy Policy have the meaning given to them in our Terms of Service.</p>
              <p data-aos="fade-up">Regulatory Compliance We strive to adhere to U.S. federal and certain state regulations. This includes, but may not be limited to, FERPA, COPPA, SOPPA/ 105 IL CS85, and California AB 1584. We highly recommend that you read our policies and terms of service to ensure that we adhere to your localregulatory needs, as we make no guarantee of compliance for your specific needs. If you have questions about how we handle User Data, please email us at partners@FENFO.com.</p>
              <p data-aos="fade-up"><b>How we collect and use data</b></p>
              <p data-aos="fade-up">We take the information you provide to us very seriously, and we strive to put you in control of decisions around your information.</p>
              <p data-aos="fade-up">FENFO collects the following information about you and your use of our platform: Personal Information.</p>
              <p data-aos="fade-up">When you partner with FENFO, you may provide to FENFO what is generally called “personally identifiable information” or “personal data that can be used to identify you. At FENFO, we call this data “Personal Information.”</p>
              <p data-aos="fade-up">Information from Integrated Services. You may also share additional information with FENFO through an Integrated Service, API, or FTP. If you choose to provide such information during onboarding or otherwise, you are giving FENFO the permission to use, share, and store it in a manner consistent with this Privacy Policy.</p>
              <p data-aos="fade-up">Information about your use of our technology and other User-provided Information. We may collect information about your use of certain features on our platform, such as the number and types of report queries executed, etc. This enables us to better tailor experiences that are most appropriate for you.</p>
              <p data-aos="fade-up">Information obtained from other Users. We make available certain features through our technology that allow other Users to provide us with information about you. This information may include Personal Information. Generally, this occurs when administrators and teachers provide information about a learner. For example, an administrator may provide information, such as the learner’s first and last name, for use within our platform.</p>
              <p data-aos="fade-up">Location Information. We may collect and use information about your location (such as your city or school) to help us in aggregating the predictive analytics models that are precise in their learning, but we don’t collect the precise geolocation of you or your device.</p>
              <p data-aos="fade-up">Information from Other Sources. In certain situations, we may obtain information, including Personal Information, from third parties or sources other than our platform. If we combine or associate information from other sources with Personal Information that we collect through our platform, we will treat the combined information as Personal Information in accordance with this Privacy Policy.</p>
              <p data-aos="fade-up">FENFO uses this information in the following ways: To enhance our technology and the services we provide. FENFO uses the information you provide or that we collect to enhance our relationship with you and to operate, maintain, enhance, and provide all of the features and services found on our platform. If you have given FENFO consent, we may use your Personal Information to provide you with information about FENFO’s features, services, and other offerings that may be of interest to you. Under certain circumstances and if we obtain your consent (for example, if you submit a testimonial and agree to make it public), we maypost your Personal Information on our platform and other third-party platforms.</p>
              <p data-aos="fade-up">To understand how you and other Users use our platform. FENFO uses all of the information that you provide or that we collect from Users to understand and analyze our user&apos;s usage trends, learning behaviors, and preferences to improve the way the platform works and looks and to create new features and functionality.</p>
              <p data-aos="fade-up">To enable your participation in FENFO partnership arrangements. To enable your participation in FENFO partnership arrangements. FENFO will not share Personal Information with other third-party organizations for their marketing or promotional use without your consent or as part of a specific program or feature for which you can opt in. You can permit us to share your Personal Information with authorized partners, not-for-profit organizations, and other entities not affiliated with FENFO. In these cases, we will only provide to these third parties the information you have authorized or asked us to share with these third parties.</p>
              <p data-aos="fade-up">Data Retention. A core part of our service is to relay data to school administrators and other authorized stakeholders. Because of this, school organizations frequently need to look back at previously collected data, whether the user is still active or not. For these purposes, we will retain your information for as long as your account is active, as is authorized by your school organization, or as is reasonably useful for your school organization’s potential use. An authorized school representative, or you if so authorized or using for personal reasons, may request deletion of your account and data by emailing partners@FENFO.com. If the account is no longer active andthe school organization has not requested the data within 10 years, we will purge your data.</p>
              <p data-aos="fade-up"><b>Data Breach Response Plan DEFINITIONS</b></p>
              <p data-aos="fade-up">Data breach: when personal information held by FENFO is lost or subjected to unauthorized access, modification, disclosure, or other misuse or interference. Examples of a data breach are when a device containing a student&apos;s personal information is lost or stolen, FENFO’s database is hacked, or FENFO mistakenly provides personal information to the wrong person. Data breaches are not limited to malicious actions, such as theft or ‘hacking,’ but may arise from internal errors or failure to follow information handling policies that cause accidental loss or disclosure.</p>
              <p data-aos="fade-up">Loss: Accidental or inadvertent loss of personal information held by FENFO in circumstances where it is likely to result in unauthorized access or disclosure.</p>
              <p data-aos="fade-up">Unauthorized access: when personal information that FENFO holds is accessed by someone who is not permitted to have access. This includes unauthorized access by an external third party (such as hacking).</p>
              <p data-aos="fade-up">Unauthorized disclosure: when FENFO makes personal information accessible or visible to others outside FENFO, and releases that information from its effective control in a way that is not permitted by FERPA, SOPIPA, and SOPPA.</p>
              <p data-aos="fade-up"><b>DATA BREACH RESPONSE</b></p>
              <p data-aos="fade-up">Validate the data breach</p>
              <ul>
                <li data-aos="fade-up">Examine the initial information and available logs to confirm that a breach has occurred.</li>
                <li data-aos="fade-up">The date, time, duration, and location of the breach</li>
                <li data-aos="fade-up">The type of personal information involved in the breach</li>
                <li data-aos="fade-up">The cause and extent of the breach</li>
                <li data-aos="fade-up">A list of the affected individuals or possible affected individuals</li>
                <li data-aos="fade-up">The risk of serious harm to the affected individuals</li>
                <li data-aos="fade-up">The risk of other harms</li>
              </ul>
              <p data-aos="fade-up">Assemble an incident response team</p>
              <ul>
                <li data-aos="fade-up">Team includes management, information technology, legal, media relations, and risk management representatives.</li>
                <li data-aos="fade-up">Immediately determine the status of the breach (on-going, active, or post breach).</li>
                <li data-aos="fade-up">If the breach is active or ongoing, prevent further data loss by securing and blocking unauthorized access to systems or data and preserving evidence for investigation.</li>
                <li data-aos="fade-up">Document all mitigation efforts for later analysis.</li>
                <li data-aos="fade-up">Advise staff informed of the breach to keep breach details in confidence until notified otherwise.</li>
              </ul>
              <p data-aos="fade-up">Determine the scope of the breach</p>
              <ul>
                <li data-aos="fade-up">If criminal activity is suspected, notify law enforcement and follow any applicable federal, state, or local legal requirements relating to the notification of law enforcement.</li>
              </ul>
              <p data-aos="fade-up">Notify the data owners</p>
              <ul>
                <li data-aos="fade-up">Reach out to data owners as soon as possible to notify them about the breach.</li>
                <li data-aos="fade-up">Foster a cooperative relationship between the incident response team and data owners.</li>
                <li data-aos="fade-up">Work collaboratively with data owners to secure sensitive data, mitigate the damage that may arise from the breach, and determine the root cause(s) of the breach to devise mitigating strategies and prevent future occurrences.</li>
              </ul>
              <p data-aos="fade-up">Prevent Future Breaches</p>
              <ul>
                <li data-aos="fade-up">Full investigation of the cause of the breach</li>
                <li data-aos="fade-up">Report to the Leadership Team and make recommendations:</li>
                <li data-aos="fade-up">Update security and response plan if necessary</li>
                <li data-aos="fade-up">Make appropriate changes to policies and procedures if necessary</li>
                <li data-aos="fade-up">Revise and update FENFO staff training practices if necessary</li>
              </ul>
              <p data-aos="fade-up">Technical Information. To provide a personalized and high-quality experience for our users, we may use various technologies that automatically record technical information from your browser or device, including standard log files, web beacons, or pixel tags. This technical information may include your Internet Protocol (IP) address, device or browser type, Internet service provider (ISP), referring or exit pages, clickstream data, operating system, and the dates and times you visit the Website. We do this to understand better how our Users are using our Website so we can improve site functionality and the services we offer you. Like most websites, whether or not you are a registered member, we may send one or more cookies – small text files containing a string of alphanumeric characters – to your computer. Cookies remember information about your activities on a website and enable us to provide you with a more Personalized Learning Playlist experience. FENFO may use both session cookies and persistent cookies. A session cookie disappears automatically after you close your browser. A persistent cookie remains after you close your browser and may be used by your browser on subsequent visits to the Website. You can, however, remove a persistent cookie at any time. Please review your web browser “Help” file to learn the proper way to modify your cookie settings. However, without cookies, you will not have access to certain services and features on the Website.</p>
              <p data-aos="fade-up">FENFO uses a variety of third-party service providers, such as Amazon Web Services and Google Analytics, to understand our Website usage. We may allow third-party service providers to place and read their own cookies, web beacons, and similar technologies to collect information through the Website. These third parties collect this information directly and automatically, and FENFO does not participate in these data transmissions. FENFO will only work with third-party service providers who have proven, or of whom FENFO has reasonable expectation, that they adhere to at least the same principles as this privacy policy. FENFO also may use Local Storage Objects (LSOs) such as HTML5 to store content information and preferences. Third parties with whom we partner to provide certain features on our site may use LSOs such as HTML5 to collect and store information. Various browsers may offer management tools for removing HTML5 LSOs. Please consult your browser’s “Help” function to learn more.</p>
              <p data-aos="fade-up">How we share or transfer data. FENFO takes great care to protect the information you provide us. We do not rent or sell Personal Information that we collect from Users with third parties. We also take great measures to restrict any collection or disclosure of Personal Information from children less than 13 years of age.</p>
              <p data-aos="fade-up">FENFO will disclose User information only as described below: If you want information shared with other Users, we’ll share it with you. We provide certain features that may allow you to share information with other Users. For example, if you are an administrator, you may want to share a report with another administrator with your name, school, and grades, and subjects. Whenever you share information with other Users of our platform, any Personal Information that you choose to include in, or is associated with, such User Postings will be accessible by such Users. As with most online services, once you make your Personal Information available to others in any of these ways, it may be collected and used by the recipients without restriction.</p>
              <p data-aos="fade-up">We may share data with third-party applications or persons that you authorize. In the future, Third-party application developers and service providers (commonly known as “App Developers“) may build complementary services for our platform. You may request we share your information with App Developers by connecting to the application or service and approving access to your FENFO account.</p>
              <p data-aos="fade-up">We may share anonymous or aggregate data to improve our services and learn more about our Users. On certain occasions, FENFO may work with business partners to improve our services or offerings. We may disclose automatically collected and other aggregate non-Personal Information to authorized business partners, conduct research on online education, or assist in understanding the usage, viewing, and demographic patterns for certain programs, content, services, promotions, and/or functionality on our platform.</p>
              <p data-aos="fade-up">We will share data when required by law. FENFO may also disclose User information if required to do so by law, or if we have a good-faith belief that such action is necessary to comply with local, state, federal, international, or other applicable laws (such as U.S. Copyright law) or respond to a court order, judicial or other government subpoenas, or warrant, or administrative request. Sometimes, we may make such disclosures without first providing notice to Users.</p>
              <p data-aos="fade-up">We may share data in the context of a change of business, including a merger or acquisition. If FENFO is acquired by or merged with a third-party entity, we may transfer or assign the information we have collected from Users as part of such merger, acquisition, sale, or other change of control. We will only transfer this information in one of the following cases: The Successor Entity does not reduce our security and privacy practices concerning student data. One way to achieve this is through the entity similarly signing the Student Data Privacy Pledge. If, after we send a notice telling Users of the sale and potential transfer of data and giving them the option to deny the data transfer, a User has not replied within 15 days.</p>
              <p data-aos="fade-up">We may share data when necessary or appropriate to protect FENFO or others. FENFO may disclose information that we believe, in good faith, is appropriate or necessary to take precautions against liability; to protect FENFO from fraudulent, abusive, or unlawful uses; to investigate and defend ourselves against any third-party claims or allegations; to assist government enforcement agencies; to protect the security or integrity of our platform; or to protect the rights, property, or personal safety of FENFO, our Users, or others.</p>
              <p data-aos="fade-up">Limitations on Access to your Personal Information by Employees and Authorized Parties. FENFO’s employees, agents, and contractors must have a legitimate business reason to access Personal Information provided to FENFO. We may share your Personal Information with third-party service providers, including outside contractors or agents who help us manage our information activities, but they may only use your Personal Information to provide us with a specific service and not for any other purpose. Where feasible, FENFO will require our third-party service providers to comply with this Privacy Policy.</p>
              <p data-aos="fade-up">General Policies on Working with Third Parties. When dealing with Third Parties in any data transfer context mentioned above, we will only do so if they adhere to similar privacy policies to ourselves, safeguarding student data at a similar or definitively same level to the Student Data Privacy Pledge.</p>
              <p data-aos="fade-up">Your choice and options in our data collection, use, and transfer You can choose to not provide us with Personal Information. You may always decline to share your Personal Information with FENFO. Registration may not be required to access many portions of our platform. If you decline to register, however, FENFO will not be able to provide to you certain features and functionalities found on our platform. You may later enable or access those features by providing FENFO with the necessary Personal Information.</p>
              <p data-aos="fade-up">You can edit or delete Personal Information in our records. We want you to have access to your information so that you can help keep it as accurate as possible. If you register and provide FENFO with Personal Information, you may update your account and information at any time by reviewing your profile information. To delete your account permanently or make other changes, email partners@FENFO.com.</p>
              <p data-aos="fade-up">You can disconnect us from Integrated Services. You may revoke FENFO’s access to your account on any Integrated Service, such your Student Information System, at any time by updating the appropriate settings in the respective Integrated Service account preferences. You should check your privacy settings on each Integrated Service to understand and change the information sent to us through each Integrated Service. Please review each Integrated Service’s terms of use and privacy policies carefully before using their services and connecting to our platform.</p>
              <p data-aos="fade-up">California Children’s Privacy Rights. If you are under 18, or the parent of a User under 18, residing in California, you are entitled to request removal of content or information on our platform. If you would like to request the removal of your or your child’s content or information, please email us at partners@FENFO.com. for assistance. Please note that removal of your content or information does not ensure complete or comprehensive removal, as there may be de-identified or recoverable elements of your content or information on our servers in some form. Additionally, we will not remove content or information that we may be required to retain under applicable federal and state laws.</p>
              <p data-aos="fade-up">Our appReturn On Academics ®ch to Data Security is important to you and us. To protect your privacy and security, we take reasonable steps to verify your identity before granting you account access or making corrections to your information. For example, we may ask you to provide certain Personal Information to confirm your identity, and we may require that you create and use a password to access certain parts of our platform. You should create and maintain a strong password to help ensure the security of your account.</p>
              <p data-aos="fade-up">We try to ensure that our platform and information sent to us are safe, but no security measures are perfect. FENFO uses certain physical, managerial, and technical safeguards designed to preserve the integrity and security of your Personal Information and other information we maintain in connection with our platform. We cannot, however, ensure or warrant the security of any or all of the information you transmit to FENFO, and you do so at your own risk. Once we receive your transmission of information, FENFO makes commercially reasonable efforts to ensure the security of our systems. When you enter sensitive information, we encrypt the transmission of that information using secure socket layer technology (SSL) or similar technologies. However, please note that this is not a guarantee that such information may not be accessed, disclosed, altered, or destroyed by breach of any of our physical, technical, or managerial safeguards.</p>
              <p data-aos="fade-up">We will notify you electronically or via the platform if FENFO experiences a data security incident that could affect you. If we learn of a data security incident that compromises or appears to compromise your Personal Information, then we will attempt to notify you electronically so that you can take appropriate protective steps. We may also post a notice on our platform if a data security incident occurs.</p>
              <p data-aos="fade-up">How we maintain data integrity. FENFO only uses Personal Information as needed for the purposes for which it was collected or where you have consented to our use of Personal Information relating to you. We take reasonable steps to ensure that the Personal Information we store and use is accurate, complete, and up-to-date. If you discover that Personal Information or other data pertaining to you is inaccurate, incomplete, or out-of-date, please update your account information or contact us as outlined below.</p>
              <p data-aos="fade-up">Links to other sites. The platform may link to and may be linked by websites operated by other entities or individuals. Some of these websites, such as the FENFO Facebook page, may be co-branded with our name or logo. This Privacy Policy does not apply to, and we cannot always control the activities of, such other third-party websites. You should consult the respective privacy policies of those third-party websites.</p>
              <p data-aos="fade-up">International visitors. Our platform is operated and managed on servers located within the United States. Suppose you choose to use our platform from the European Union or other regions of the world with laws governing data collection and use that differ from U.S. law. In that case, you acknowledge and agree that you are transferring your Personal Information outside of those regions to the United States. By providing your Personal Information on the platform, you consent to that transfer. In some special requirements, we may be able to create and manage isolated servers outside of the United States based on specific international partnerships. Please contact us at partners@FENFO.com. regarding this requirement.</p>
              <p data-aos="fade-up"><b>Changes and updates to this Privacy Policy.</b></p>
              <p data-aos="fade-up">FENFO may modify or revise this Privacy Policy from time to time. FENFO will notify Users of any changes to our Privacy Policy by posting the revised Privacy Policy with an updated date of revision on our platform.</p>
              <p data-aos="fade-up">Contact FENFO Please contact FENFO with any questions or comments about this Privacy Policy, your personal information, our third-party disclosure practices, or your consent choices by email at partners@FENFO.com. or by submitting a question using our <Link to={'/signup'}>Sign Up</Link>.</p>
            </TextBlock>
        </div>
    </div>
  )
}

export default PrivacyPolicyPage