import TextBlock from '../../components/TextBlock';
import classes from './terms-and-conditions.module.scss';

const TermsPage = () => {
  return (
    <div className={classes.wrapper}>
        <div className={`container ${classes.wrapper_container}`} data-aos="fade-up">
            <h2 className={classes.wrapper_ttl}>Terms & Condition</h2>
            <span data-aos="fade-up" className={classes.wrapper_update}>Last Updated August 1, 2022</span>
            <h4 data-aos="fade-up" className={classes.wrapper_ttl_sub}>Introduction</h4>
            <TextBlock classWrap={classes.wrapper_text}>
              <p data-aos="fade-up">The following describes the terms on which FENFO.COM (referred to herein as “FENFO,” “we,” or “us”) offer you access to our services. Your permission to use the FENFO platform, and the licenses granted herein, are expressly conditioned upon your acceptance of these Terms of Service and the following additional terms and conditions and policies, which are hereby incorporated by reference (collectively, the “Agreement”)</p>
              <p data-aos="fade-up"><b>1. Description of Service.</b></p>
              <p data-aos="fade-up">FENFO is an innovative technology company that leverages machine learning and predictive analytics to aggregate the return on investment, Return On Academics ®, employee engagement, and software adoption rates based on technology usage data. This service provides district administrators, and human resources managers access to detailed insights to help optimize their spending, improve student academic outcomes, evaluate programs, retain employees, improve sales enablement and increase company revenue. FENFO owns all the data collected and aggregated for machine learning and predictive analytics.</p>
              <p data-aos="fade-up">This Terms of Service/User Agreement (“Agreement”) governs your access to and use of the FENFO platform. The FENFO Service is publicly available to all School Districts, corporations, and government agencies that are subscribed and have an active license. By partnering with FENFO or using the Service in any manner, including, but not limited to, by visiting the www.FENFO.com website, you agree to the terms stated in this Agreement.</p>
              <p data-aos="fade-up">This Terms of Service applies to both visitors and partners. You may not hack, deface or otherwise misuse the site, or attempt to gain unauthorized access to restricted parts of the site or the technology used to create it. You may link to any page(s) on this site, but please keep in mind that URLs may change without notice, and any links must be in full compliance with applicable laws. FENFO may terminate your use of this site at any time, without notice, if you fail to adhere to these terms or otherwise in FENFO Network&apos;s sole discretion.</p>
              <p data-aos="fade-up">A. Restricted Areas</p>
              <p data-aos="fade-up">Certain parts of our site are password-protected. You agree to furnish accurate information to obtain your password and update it as it changes. Protection of your password is your responsibility. By obtaining a password, you authorize us to honor instructions from any person using that password as if you had given the instructions. All actions taken by the use of your password will be your responsibility. We reserve the right to cancel your password and remove your access to restricted areas at our sole discretion. </p>
              <p data-aos="fade-up">While FENFO uses security measures to protect your password and other personal information from unauthorized access, you are also responsible for protecting and securing your password.</p>
              <p data-aos="fade-up">The information you receive when visiting a restricted area of our site is confidential and proprietary information of FENFO.</p>
              <p data-aos="fade-up">Your use of FENFO&apos;s confidential information is governed by the terms of any non-disclosure or confidentiality agreement between us and the terms on this website.</p>
              <p data-aos="fade-up">Suppose you download software and any artifacts from this site, including software updates. In that case, they are provided to you pursuant to (i) the terms accompanying the file or (ii) if there are no terms with the file, the terms of the license agreement which accompanied the original product licensed by you which you are updating.</p>
              <p data-aos="fade-up"><b>2. Fees, Services, Pricing, and Payments. Partners (School districts, corporations, government agencies)</b></p>
              <p data-aos="fade-up">Subject to the terms and conditions of this Agreement and any agreement entered into by your institution relating to our offerings, FENFO grants you a limited, non-exclusive, non-transferable license to access and use the platform on an annual subscription basis. You shall not (a) copy the Product or any part, feature, function, or user interface thereof (b) use the Product to store or transmit infringing, libelous, or otherwise unlawful or tortious material, or to store or transmit material in violation of third-party privacy rights (c) attempt to gain unauthorized access to the Product or its related systems or networks; and (d) reverse engineer the Product (to the extent such restriction is permitted by law). You agree, further, not to use or attempt to use any engine, software, tool, agent, or other device or other mechanisms (including without limitation browsers, spiders, robots, avatars, or intelligent agents) to navigate or search the Products or Content.</p>
              <p data-aos="fade-up">A. Electronic Signatures and Contracts.</p>
              <p data-aos="fade-up">YOU ACKNOWLEDGE THAT YOUR ELECTRONIC SUBMISSIONS CONSTITUTE YOUR AGREEMENT AND INTENT TO BE BOUND BY ELECTRONIC SUBMISSIONS APPLIES TO ALL RECORDS RELATING TO ALL TRANSACTIONS YOU ENTER INTO ON THIS SITE, INCLUDING NOTICES OF CANCELLATION, POLICIES, CONTRACTS, AND APPLICATIONS. To access and retain your electronic records, you may be required to have certain hardware and software, which are your sole responsibility.</p>
              <p data-aos="fade-up">B. Refund Policy</p>
              <p data-aos="fade-up">All sales are final, and no refunds are available. FENFO may, in its sole discretion, make certain exceptions to this policy on a case-by-case basis. For example, suppose such an exception is made. In that case, FENFO may issue the buyer a refund in a manner it deems appropriate, including without limitation in the form of SWYE credit or prorating.</p>
              <p data-aos="fade-up"><b>3. Registration Obligations.</b></p>
              <p data-aos="fade-up">In consideration of your use of the Service, you represent that you are at least 18 years of age and are not a person barred from receiving these services under the laws of the United States or other applicable jurisdiction. You also agree to (a) provide true, accurate, current, and complete information about yourself as prompted by the Service&apos;s registration form, and (b) maintain and promptly update the Member Data to keep it true, accurate, current, and complete at all times. If you provide any information that is untrue, inaccurate, not current, or incomplete, or if FENFO has reasonable grounds to suspect that such information is untrue, inaccurate, not current, or incomplete, without limiting any other remedies, FENFO has the right to suspend or terminate your Partner Account and refuse any current or future use of the Service (or any portion thereof). Please see our Privacy Policy for further information.</p>
              <p data-aos="fade-up"><b>4. Partner and Visitor Conduct.</b></p>
              <p data-aos="fade-up">As a condition of using the Service, Partners and visitors agree to all of the following:</p>
              <ul>
                <li data-aos="fade-up">You must be a registered partner to access the Service.</li>
                <li data-aos="fade-up">You are responsible for maintaining the confidentiality of your username and password. You should not disclose your password to anyone.</li>
                <li data-aos="fade-up">You are responsible for maintaining the confidentiality of all the data you have access to for your particular school, district, company and or government agency. You should not disclose this data to anyone outside your organization other than FENFO.</li>
                <li data-aos="fade-up">You are responsible for all activity that occurs under your Username.</li>
                <li data-aos="fade-up">You are solely responsible for your conduct and information that you submit on the platform, submitted, or displayed on the Service under your Username.</li>
                <li data-aos="fade-up">You agree that you will not attempt to, nor encourage or assist any other person to, circumvent or modify any system, security technology, or other software that is part of the Service or used to administer the rules contained in this Agreement.</li>
              </ul>
              <p data-aos="fade-up">Further, while using the Service, Partners and visitors agree not to:</p>
              <ul>
                <li data-aos="fade-up">upload, post, email, transmit, or otherwise make available any content, material, or information to, on, or through the Service that is fraudulent, unlawful, harmful, threatening, abusive, harassing, tortious, defamatory, vulgar, obscene, libelous, pornographic, profane, sexually explicit or indecent, invasive of another’s privacy, hateful, or racially, ethnically, orotherwise objectionable;</li>
                <li data-aos="fade-up">transmit any worms or viruses, spyware, malware, or any other harmful or destructive code;</li>
                <li data-aos="fade-up">violate any applicable federal or local laws in your jurisdiction (including but not limited to intellectual property laws or tax laws);</li>
                <li data-aos="fade-up">use the Service for any illegal or unauthorized purpose;</li>
                <li data-aos="fade-up">impersonate any person or entity, including, without limitation, a FENFO employee or user, or falsely state or otherwise misrepresent your affiliation with a person or entity;</li>
                <li data-aos="fade-up">transmit email or any other content that includes personal or identifying information about another person without that person’s explicit consent;</li>
                <li data-aos="fade-up">transmit email or any other content that is false, deceptive, misleading, deceitful, or constitutes “bait and switch”;</li>
                <li data-aos="fade-up">provide materials or any other content for download that contain viruses or any other code, files, or programs designed to interrupt, destroy, or limit the functionality of any computer software or hardware or telecommunications equipment;</li>
                <li data-aos="fade-up">attempt to gain unauthorized access to FENFO computer systems or engage in any activity that disrupts, diminishes the quality of, interferes with the performance of, or impairs the functionality of the Service;</li>
                <li data-aos="fade-up">attempt to regain access to FENFO following a ban or account termination, including without limitation by means of opening or attempting to open a new account under the same or different Username;</li>
                <li data-aos="fade-up">collect any personally identifying data about Users or visitors for commercial or unlawful purposes; or</li>
                <li data-aos="fade-up">use automated means, including spiders, robots, crawlers, data mining tools, or the like to download data from the Service-except for internet search engines (e.g., Google or Yahoo!) and non-commercial public archives (e.g., archive.org) that comply with our robots.txt file, or that are “well-behaved” web services/RSS/Atom, clients. We reserve the right to define what we mean by “well-behaved,” and to develop, invoke, or utilize any means to disrupt, diminish the quality of, interfere with the performance of, or impair the functionality of any automated means you may use to access the Service.</li>
              </ul>
              <p data-aos="fade-up"><b>5. Links to Other Sites and Resources.</b></p>
              <p data-aos="fade-up">The Service may contain links to other websites or resources. FENFO has no control over such external sites and resources. You agree that (i) FENFO is not responsible for the availability or accuracy of such external sites and resources, and (ii) FENFO does not endorse nor is it responsible or liable for any content, advertising, products, services, or materials on or available from such external sites and resources. Any reliance on the contents or services of such an external website or resource is done at your own risk, and you assume all responsibilities and consequences resulting from such reliance.</p>
              <p data-aos="fade-up"><b>6. Privacy Policy</b></p>
              <p data-aos="fade-up">We take the privacy of our users and Partners’ information very seriously. Our Privacy Policy is available at FENFO Privacy Policy . By accepting these Terms of Service, you agree to be bound by our Privacy Policy, which is by this reference expressly incorporated into this Agreement.</p>
              <p data-aos="fade-up"><b>7. Indemnity</b></p>
              <p data-aos="fade-up">By accepting this Agreement, you agree to indemnify and hold FENFO and its subsidiaries, affiliates, officers, agents, employees, partners, and licensors harmless from any claims, demands, liabilities, expenses, or tax assessments, including reasonable attorneys’ fees, arising out of any claim made by any third party or any action taken by any governmental or regulatory body (including, without limitation, the Federal Trade Commission or any state attorney general), (i) your use of the Service, (ii) your connection to the Service, (iii) your actual or alleged breach of this Agreement (including our Copyright Policy and Privacy Policy), (iv) your actual or alleged infringement of any third party intellectual property or proprietary rights, or (vi) your actual or alleged violation of any applicable laws, rules, regulations, or rights of another.</p>
              <p data-aos="fade-up"><b>8. Warranty Disclaimers</b></p>
              <p data-aos="fade-up">YOU AGREE THAT THE SITE AND THE SERVICE ARE PROVIDED ON AN “AS IS” AND “AS AVAILABLE” BASIS, AND THAT YOUR USE OF THE SERVICE PROVIDED BY FENFO SHALL BE AT YOUR SOLE RISK. TO THE FULLEST EXTENT PERMITTED BY LAW, FENFO, ITS AFFILIATES, AND ITS AND THEIR OFFICERS, DIRECTORS, EMPLOYEES, AND AGENTS DISCLAIM ALL WARRANTIES, EXPRESS OR IMPLIED, IN CONNECTION WITH THE WEBSITE, THE SERVICE, AND YOUR ACCESS TO AND USE THEREOF, INCLUDING WITHOUT LIMITATION ANY IMPLIED WARRANTY OF MERCHANTABILITY, TITLE, NON-INFRINGEMENT, OR ANY IMPLIED WARRANTY ARISING FROM COURSE OF DEALING OR USAGE OF TRADE.</p>
              <p data-aos="fade-up"><b>9. Limitation of Liability</b></p>
              <p data-aos="fade-up">YOU AGREE THAT FENFO, ITS AFFILIATES, AND ITS AND THEIR OFFICERS, DIRECTORS, EMPLOYEES, AND/OR AGENTS SHALL NOT BE LIABLE TO YOU FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR EXEMPLARY DAMAGES, INCLUDING, BUT NOT LIMITED TO, DAMAGES FOR LOSS OF PROFITS, GOODWILL, REPUTATION, USE, OR DATA OR OTHER INTANGIBLE LOSSES, RESULTING FROM: (I) THE ACCESS TO, USE, OR THE INABILITY TO ACCESS OR USE THE SERVICE; (II) UNAUTHORIZED ACCESS TO OR ALTERATION OF YOUR TRANSMISSIONS OR DATA; (III) STATEMENTS OR CONDUCT OF ANY THIRD PARTY ON THE SERVICE; OR (IV) ANY OTHER MATTER RELATING TO THE SERVICE. SOME STATES OR OTHER JURISDICTIONS DO NOT ALLOW THE EXCLUSION OR LIMITATION OF LIABILITY FOR INCIDENTAL OR CONSEQUENTIAL DAMAGES, SO THE ABOVE LIMITATIONS AND EXCLUSIONS MAY NOT APPLY TO YOU. FENFO’S LIABILITY TO YOU OR ANY THIRD-PARTY SHALL IN NO EVENT BE, IN THE AGGREGATE, GREATER THAN THE LESSER OF (A) THE TOTAL AMOUNTS PAID BY YOU TO FENFO DURING THE TWELVE (12) MONTHS PRIOR TO THE CLAIM OR ACTION ALLEGEDLY GIVING RISE TO SUCH LIABILITY, OR (B) ONE HUNDRED DOLLARS ($100.00). YOU HEREBY ACKNOWLEDGE THAT YOU UNDERSTAND THAT BY ACCESSING AND USING THE SERVICE AND AGREEING TO THE TERMS OF THIS AGREEMENT, YOU MAY BE WAIVING RIGHTS WITH RESPECT TO CLAIMS THAT ARE AT THIS TIME UNKNOWN OR UNSUSPECTED.</p>
              <p data-aos="fade-up">IF YOU ARE A CALIFORNIA RESIDENT, YOU ACKNOWLEDGE THAT YOU HAVE READ AND UNDERSTOOD, AND HEREBY EXPRESSLY WAIVE, THE SECTION 1542 OF THE CIVIL CODE OF CALIFORNIA, WHICH PROVIDES AS FOLLOWS: “A GENERAL RELEASE DOES NOT EXTEND TO CLAIMS WHICH THE CREDITOR DOES NOT KNOW OR SUSPECT TO EXIST IN HIS FAVOR AT THE TIME OF EXECUTING THE RELEASE, WHICH IF KNOWN BY HIM MUST HAVE MATERIALLY AFFECTED HIS SETTLEMENT WITH THE DEBTOR.” FURTHERMORE, IF YOU ARE A RESIDENT OF ANOTHER STATE OR JURISDICTION, YOU AGREE TO WAIVE IN ADVANCE ANY SIMILAR LAWS OF SUCH OTHER STATE OR JURISDICTION.</p>
              <p data-aos="fade-up"><b>10. Termination</b></p>
              <p data-aos="fade-up">We reserve the right to suspend, terminate, or take any other action or remedy that we deem reasonable, appropriate, or necessary, in our sole discretion, concerning your account immediately, without prior notice or liability, for any reason. Your right to use the Service will immediately cease if we terminate your account. You may terminate your Partner Account at any time and for any reason, and we will make available through the Service reasonable means for you to do so. When these terms end, those terms intended to continue indefinitely will continue to apply, including but not limited to ownership provisions, licenses, warranty disclaimers, indemnity, and limitations of liability.</p>
              <p data-aos="fade-up"><b>11. Miscellaneous Provisions</b></p>
              <ul>
                <li data-aos="fade-up">Ownership of Site. The Service, and all text, graphics, user interfaces, visual interfaces, photographs, trademarks, logos, artwork, content, and computer code therein (collectively, the “FENFO Content”), including without limitation the design, structure, selection, coordination, expression, “look and feel,” and arrangement of such Content is owned, controlled, or licensed by or to FENFO, and is protected by trade dress, trade secret, copyright, patent, and trademark laws, and various other intellectual property rights. Except as expressly provided in this Agreement or otherwise permitted by law, no FENFO Content may be used, copied, reproduced, modified, republished, disassembled, reverse engineered, uploaded, posted, publicly displayed, publicly performed, encoded, translated, transmitted, or distributed in any way to any other person, computer, server, website, or in any other medium for any purpose, without FENFO’s express prior written consent.</li>
                <li data-aos="fade-up">Entire Agreement. The Terms of Service, including FENFO’s Privacy Policy, which is incorporated by reference above, constitute the entire agreement between you and FENFO and govern your use of the Service.</li>
                <li data-aos="fade-up">No Agency. FENFO is not the agent or representative of any site users, nor does it operate under their authority for any purpose. FENFO is simply a service provider that offers users the technological means to aggregate software usage data.</li>
              </ul>
              <p data-aos="fade-up">Governing and Applicable Law. The Terms of Service will be governed by and construed in accordance with the laws of the State of Texas, in the United States of America, without regard to its conflict of law provisions. Those who choose to access the Service from other locations do so on their own initiative and are responsible for compliance with local laws if and to the extent local laws are applicable. Software from this site is further subject to United States export controls. No software from www.FENFO.com may be downloaded or otherwise exported or re-exported (i) into (or to a national or resident of) Cuba, Iran, Iraq, Libya, North Korea, Syria, or any other country to which the United States has embargoed goods; (ii) to anyone on the U.S. Treasury Department’s list of Specially Designated Nationals or the U.S. Commerce Department’s Table of Deny Orders; or (iii) in any other the manner that violates U.S. law. By downloading or using any software, you represent and warrant that you are not located in, under the control of, or a national or resident of any such country or on any such list.</p>
              <ul data-aos="fade-up">
                <li data-aos="fade-up">Dispute Resolution : Any dispute arising out of or relating to these terms or the Service shall be submitted exclusively to confidential binding arbitration in Frisco, TX, except that to the extent you have in any manner violated or threatened to violate FENFO’s intellectual property rights, we may seek injunctive or other appropriate relief in any state or federal court in the State of Texas. You hereby consent to and waive all defenses of lack of personal jurisdiction and forum non-convenient with respect to venue and jurisdiction in the state and federal courts of Texas. Arbitration under these Terms of Use shall be conducted pursuant to the Commercial Arbitration Rules then prevailing at the American Arbitration Association. The arbitrator&apos;s award shall be final and binding and may be entered as a judgment in any court of competent jurisdiction. To the fullest extent permitted by applicable law, no arbitration under this Agreement shall be joined to an arbitration involving any other party subject to this Agreement, whether through class action proceedings or otherwise. If a suit, action, arbitration, or other proceedings of any nature whatsoever is instituted in connection with any dispute or controversy arising out of or related to the subject matter of this Agreement, the prevailing party shall be entitled to recover from the non-prevailing party, in addition to any other available remedy, all reasonable costs, including without limitation court costs, attorney&apos;s fees, and other expenses incurred in such proceeding.</li>
                <li data-aos="fade-up">Waiver and Severability. The failure of FENFO to exercise or enforce any right or provision of the Terms of Service shall not constitute a waiver of such right or provision. If any provision of this Terms of Service shall be held unlawful, void, or unenforceable for any reason, then that provision shall be deemed severed from these Terms of Service and shall not affect the validity and enforceability of the remaining provisions. The severed provision shall be deemed modified so that its purpose can be lawfully effectuated and enforced.</li>
                <li data-aos="fade-up">Notices. FENFO may provide you with notices, including, without limitation, those regarding changes to the Terms of Service and other service-related announcements, by email or postings on the Service.</li>
                <li data-aos="fade-up">FENFO may change or amend these Terms. If we make material changes, we will notify you through the user interface, in an email notification, or through other reasonable means. Your use of the Service after the date such change(s) become effective will constitute consent to the changed terms. If you disagree with the changes, you must immediately stop using the Service. Otherwise, the new terms will apply to you.</li>
                <li data-aos="fade-up">Future Changes in the Service. FENFO reserves the right at any time (and from time to time) to modify, suspend, or discontinue providing the Service or any part thereof with or without notice. FENFO will not be liable to you or to any third party for any modification, suspension, or discontinuance of the Service.</li>
              </ul>
              <p data-aos="fade-up">Assignment. FENFO may assign this agreement to any successor or a purchaser of FENFO or all or substantially all of its assets.</p>
              <ul>
                <li data-aos="fade-up">Headings. Section titles and headings in this Agreement are for convenience only, and have no legal or contractual effect.</li>
                <li data-aos="fade-up">Contact Information. Please send any questions or comments, to Customer Service, or to report any violations of this Agreement to our support team here.</li>
              </ul>
            </TextBlock>
        </div>
    </div>
  )
}

export default TermsPage